# Generated by Django 2.2.4 on 2019-10-14 11:59
# ruff: noqa

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="content_nomad",
            field=models.BooleanField(
                default=False,
                help_text="Digital Schools Android App",
                verbose_name="NomadEducation",
            ),
        ),
    ]
