# Generated by Django 2.0.7 on 2018-07-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180703_0938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('kind', 'size')},
        ),
    ]
