# Generated by Django 2.0.7 on 2018-07-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20180703_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='manager.Address'),
            preserve_default=False,
        ),
    ]
