# Generated by Django 2.2.16 on 2020-11-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20201102_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='size',
            field=models.BigIntegerField(blank=True),
        ),
    ]
