# Generated by Django 2.2.16 on 2020-11-11 11:58
# ruff: noqa

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0011_passwordresetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetcode",
            name="code",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
