# Generated by Django 3.2.21 on 2023-09-29 16:03

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20230914_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-id'], 'verbose_name': 'address', 'verbose_name_plural': 'addresss'},
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(help_text='Used only within the Imager', max_length=100, verbose_name='Address Name'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='admin_password',
            field=models.CharField(default='admin-password', help_text='To manage Clock, EduPi and Wikifundi', max_length=31, validators=[manager.models.validate_admin_pwd], verbose_name='Admin password'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(help_text='Used <strong>only within the Imager</strong>', max_length=100, verbose_name='Config Name'),
        ),
    ]
