# Generated by Django 4.2.5 on 2023-10-13 09:31

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0021_auto_20230929_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="config_yaml",
            field=models.TextField(default="", verbose_name="YAML Config"),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "French")],
                default="en",
                help_text="Hotspot interface language",
                max_length=3,
                validators=[manager.models.validate_language],
                verbose_name="Language",
            ),
        ),
    ]
