# Generated by Django 4.2.5 on 2023-12-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0022_order_config_yaml_alter_configuration_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="content_metrics",
            field=models.BooleanField(
                default=False,
                help_text="Statistiques d'utilisation du Hotspot",
                verbose_name="Hotspot Metrics",
            ),
        ),
    ]
