# Generated by Django 4.2.5 on 2024-01-03 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0023_configuration_content_metrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="branding_css",
        ),
    ]
