# Generated by Django 4.2.5 on 2024-01-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0024_remove_configuration_branding_css"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="content_edupi",
            field=models.BooleanField(
                default=False,
                help_text="Share arbitrary files with all users",
                verbose_name="File resources",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="content_edupi_resources",
            field=models.CharField(
                blank=True,
                help_text="Uncompressed ZIP folder archive of files to initialize with",
                max_length=500,
                null=True,
                verbose_name="Preloaded File Resources",
            ),
        ),
    ]
