# Generated by Django 4.2.5 on 2024-01-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0025_alter_configuration_content_edupi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="content_packages",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="content_zims",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
