# Generated by Django 5.0.3 on 2024-04-02 16:18

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0027_configuration_option_kiwix_readers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="beta_features",
            field=manager.models.JSONList(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="beta_is_active",
            field=models.BooleanField(default=False, verbose_name="Beta is active"),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="content_packages",
            field=manager.models.JSONList(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="content_zims",
            field=manager.models.JSONList(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="option_kiwix_readers",
            field=models.BooleanField(
                default=False,
                help_text="Downloadable Kiwix software for all platforms",
                verbose_name="Kiwix Readers",
            ),
        ),
    ]
