# Generated by Django 5.0.3 on 2024-04-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0028_configuration_beta_features_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="content_africatik",
        ),
        migrations.RemoveField(
            model_name="configuration",
            name="content_africatikmd",
        ),
        migrations.RemoveField(
            model_name="configuration",
            name="content_edupi",
        ),
        migrations.RemoveField(
            model_name="configuration",
            name="content_mathews",
        ),
        migrations.RemoveField(
            model_name="configuration",
            name="content_nomad",
        ),
        migrations.RemoveField(
            model_name="configuration",
            name="content_wikifundi_en",
        ),
        migrations.RemoveField(
            model_name="configuration",
            name="content_wikifundi_es",
        ),
        migrations.RemoveField(
            model_name="configuration",
            name="content_wikifundi_fr",
        ),
    ]
