# Generated by Django 5.0.10 on 2025-02-18 10:47

import manager.models
from django.db import migrations, models


def set_ssid(apps, schema_editor):
    Configuration = apps.get_model("manager", "Configuration")
    for config in Configuration.objects.all():
        config, _ = Configuration.objects.get_or_create(id=config.id)
        config.ssid = config.project_name
        config.save()


def revert(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0029_remove_configuration_content_africatik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="ssid",
            field=models.CharField(
                default="Kiwix Hotspot",
                help_text="Network SSID",
                max_length=32,
                validators=[manager.models.validate_ssid],
                verbose_name="Network name",
            ),
        ),
        migrations.RunPython(set_ssid, revert),
        migrations.AlterField(
            model_name="configuration",
            name="branding_favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=manager.models.get_branding_path,
                verbose_name="Square Logo (1MB max Image)",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="branding_logo",
            field=manager.models.ConvertedImageFileField(
                blank=True,
                null=True,
                upload_to=manager.models.get_branding_path,
                verbose_name="Horizontal Logo (1MB max Image)",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="project_name",
            field=models.CharField(
                default="kiwix",
                help_text="The landing page will also be at http://name.hotspot",
                max_length=32,
                validators=[manager.models.validate_project_name],
                verbose_name="Domain name",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="channel",
            field=models.CharField(
                choices=[("kiwix", "Kiwix")],
                default="kiwix",
                max_length=50,
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="public_warehouse",
            field=models.CharField(
                choices=[("kiwix", "download")],
                default="download",
                max_length=50,
                verbose_name="Pub WH",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="warehouse",
            field=models.CharField(
                choices=[("kiwix", "download")],
                default="kiwix",
                max_length=50,
                verbose_name="Warehouse",
            ),
        ),
    ]
