# Generated by Django 5.0.14 on 2025-08-20 18:31

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0030_configuration_ssid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="project_name",
            field=models.CharField(
                default="kiwix",
                help_text="The landing page will be at http://name.hotspot",
                max_length=32,
                validators=[manager.models.validate_project_name],
                verbose_name="Domain name",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="ssid",
            field=models.CharField(
                default="Kiwix Hotspot",
                help_text="Name of network in WiFi list (SSID)",
                max_length=32,
                validators=[manager.models.validate_ssid],
                verbose_name="WiFi Network name",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="channel",
            field=models.CharField(
                choices=[("kiwix", "Kiwix (Public)")],
                default="kiwix",
                max_length=50,
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="public_warehouse",
            field=models.CharField(
                choices=[("download", "download"), ("kiwix", "kiwix")],
                default="download",
                max_length=50,
                verbose_name="Pub WH",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="warehouse",
            field=models.CharField(
                choices=[("download", "download"), ("kiwix", "kiwix")],
                default="kiwix",
                max_length=50,
                verbose_name="Warehouse",
            ),
        ),
    ]
