# Generated by Django 5.0.14 on 2025-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0031_alter_configuration_project_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="variant",
            field=models.CharField(
                choices=[
                    ("Demo", "Demo"),
                    ("Preppers", "Preppers"),
                    ("Preppers Premium", "Preppers Premium"),
                    ("Computer", "Computer"),
                    ("Medical", "Medical"),
                    ("Wikipedia EN", "Wikipedia EN"),
                ],
                default="",
                help_text="Declared Hotspot Variant (informational)",
                max_length=24,
                verbose_name="Variant",
            ),
        ),
    ]
